name: Download release and commit
on:
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  commit-release-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download latest release asset
        uses: robinraju/release-downloader@v1
        with:
          repository: 2dust/v2rayN
          latest: true
          fileName: v2rayN-windows-64.zip
          out-file-path: ${{ github.workspace }}
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add v2rayN-windows-64.zip
          git commit -m "Add v2rayN-windows-64.zip (latest release)" || exit 0
          git push
