# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: robinraju/release-downloader@v1
        with:
          repository: '2dust/v2rayN'
          latest: true
          fileName: 'v2rayN-windows-64.zip'
          out-file-path: ${{ github.workspace }}
      - uses: actions/checkout@v4
      - name: Add downloaded file to git
        run: |
          cd /home/runner/work/test-downloader/test-downloader/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add v2rayN-windows-64.zip
          git commit -m "Add v2rayN-windows-64.zip" || echo "No changes to commit"
          git push
